### ISSUE TITLE
Doesn't work at all!

### ISSUE THREAD

**Issue by lilumi** [siteorigin/so-dev-examples#1]
Hello.
I've tried to use your documentation and  examples but it doesn't works.

there is no siteorigin_widget_register function either class SiteOrigin_Widget

Even when I changed from siteorigin_widget_register to register_widget('Hello_World_Widget'); and 
from SiteOrigin_Widget to SiteOrigin_Panels_Widget it still doesn't work.

**Comment by braamgenis** [comment]
Hi lilumi

These examples are meant to demonstrate how a WordPress plugin developer may use our Widgets Bundle plugin as a framework for creating widgets. As such, they do not function as an independent plugin, but rather as an extension of our Widgets Bundle plugin, which must be installed and activated for these examples to work. I'll try to make this clearer in the docs.

You can get the plugin either by cloning it from Github [here](https://github.com/siteorigin/so-widgets-bundle) or by downloading it from the WordPress plugin directory [here](https://wordpress.org/plugins/so-widgets-bundle/).

You can get more detailed information from our [developer docs](https://siteorigin.com/docs/widgets-bundle/getting-started-quickly/).

Hope that helps!

**Comment by Jursdotme** [comment]
I have the same problem. I can't get any of the test widgets here to load. I have the required plugins installed. They just dont show up.

**Comment by braamgenis** [comment]
Hi Jursdotme

Are you by any chance copying the whole so-dev-examples folder into your plugins folder?

The so-dev-examples folder is just a container for what is intended to be a collection of individual example plugins. Currently, however, the collection consists of only one example plugin.

So inside so-dev-examples you should see a folder named extend-widgets-bundle which has the familiar plugin structure as put forth by WordPress [here](http://codex.wordpress.org/Writing_a_Plugin#Names.2C_Files.2C_and_Locations). If you copy this folder into your plugins folder you should see the example widgets, assuming you have installed and activated the Widgets Bundle plugin.
