### ISSUE TITLE
Using in a theme

### ISSUE THREAD

**Issue by stueynet** [siteorigin/so-dev-examples#2]
Any thoughts on a good way to use this in a theme? Is it a matter of changing all the plugin file references? Do you have any advice on how to replace those with something that will work whether its its own plugin or included within the theme itself? I am working on both use cases right now.

**Comment by stueynet** [comment]
I guess more specifically is there an equivalent to 

```
plugin_dir_path(__FILE__) 
```

I could use.

**Comment by Jursdotme** [comment]
Just ran into this also. Any help would be wonderful!

**Comment by gregpriday** [comment]
Hi @stueynet, sorry I missed this question.

The equivilent to `plugin_dir_path(__FILE__)` in a theme would be `get_stylesheet_directory()` - https://codex.wordpress.org/Function_Reference/get_stylesheet_directory.
