### ISSUE TITLE
Creating custom field type

### ISSUE THREAD

**Issue by Pigrecolab** [siteorigin/so-dev-examples#3]
Hello,
I copied strictly your example for creating a custom field type "better-text", but I've these errors:
`Strict Standards:  Declaration of My_Custom_Field_Better_Text::render_field_label() should be compatible with SiteOrigin_Widget_Field_Base::render_field_label($value, $instance) in <b>C:_Lavori in corso\progetto tema\ritzy\wp-content\themes\ritzy\so_cf\better-text.class.php

Fatal error:  Declaration of My_Custom_Field_Better_Text::sanitize_field_input() must be compatible with SiteOrigin_Widget_Field_Base::sanitize_field_input($value, $instance) in <b>C:_Lavori in corso\progetto tema\ritzy\wp-content\themes\ritzy\so_cf\better-text.class.php</b> on line `

Maybe the examples is not upgraded ? How can I solve ? thanks
I add that my custom field type is in a theme and not in a plugin...

**Comment by Pigrecolab** [comment]
Hello,
I solved it just replacing  render_field_label() with render_field_label($value, $instance); the same for sanitize_field_input...

**Comment by braamgenis** [comment]
Resolved in #5
