### ISSUE TITLE
error when using this demo

### ISSUE THREAD

**Issue by xNok** [siteorigin/so-dev-examples#4]
When I install this demo plugin a can activate the widgets from the widget manager, but the I've a rey screen when editing. By inspecting this grey page I have the following html.

```
<div class="siteorigin-widget-form siteorigin-widget-form-main siteorigin-widget-form-main-my-custom-field-test-widget" id="siteorigin_widget_form_bcd160dd8258fa0c9a505fd0629c5cf0" data-class="My_Custom_Field_Test_Widget" style="display: none">
            <br>
<b>Fatal error</b>:  Declaration of My_Custom_Field_Better_Text::sanitize_field_input() must be compatible with SiteOrigin_Widget_Field_Base::sanitize_field_input($value, $instance) in <b>D:\www\wordpress\wp-content\plugins\extend-widgets-bundle\custom-fields\better-text.class.php</b> on line <b>48</b><br>
</div>
```

The issue seems very clear but I don't understand this issue. I have not found the ansers in the documentation [create a widget](https://siteorigin.com/docs/widgets-bundle/getting-started/creating-a-widget/). So I guess you made some change in the API.

**Comment by braamgenis** [comment]
Resolved in #5
