### ISSUE TITLE
How can I hide the "preview" button?

### ISSUE THREAD

**Issue by pixeline** [siteorigin/so-dev-examples#6]
Hello,

I'm developing a custom widget extending the SiteOrigin_Widget class.

Is there a built-in way to hide the "preview" button? It is not relevant in my case.

Thank you,

Alexandre.

PS: I couldn't find the former Developer's documentation. Sorry if this is the wrong place to ask this.

**Comment by braamgenis** [comment]
Hey @pixeline You could go about this in two ways.

1. The `SiteOrigin_Widget` class has a `show_preview_button()` method which you could override to return `false`.
2. (preferred method) That same method `show_preview_button()` applies a filter called `'siteorigin_widgets_form_show_preview_button'`before returning, so you can do something like `add_filter( 'siteorigin_widgets_form_show_preview_button', array( $this, '__return_false' ) );`

Hope that helps!

**Comment by pixeline** [comment]
Hello @braamgenis , 
the second method worked perfectly with the latest version of the bundle. 

Thanks a lot!

**Comment by braamgenis** [comment]
Hey @pixeline It seems I made a few mistakes in that second method. Firstly, the syntax isn't quite correct. It should be `add_filter( 'siteorigin_widgets_form_show_preview_button', '__return_false' );`. Secondly, as is, the filter will also disable the 'Preview' button for all the built-in SiteOrigin widgets. There's another method you could use to disable the preview button. The `SiteOrigin_Widget` class constructor takes a `widget_options` array as the third argument. One of the widget options is 'has_preview', which you can set to `false` to disable the 'Preview' button for only your specific widget. E.g

```
class My_Widget extends SiteOrigin_Widget {

	public function __construct() {
		parent::__construct(
			'my-widget',
			__('My Widget', 'my-widget'),
			array(
				'has_preview' => false,
			),
			array(),
			array()
		);
	}
}
```

**Comment by pixeline** [comment]
Ah, I figured the __return_false myself but did not check for the second issue. 
the fix, using the available API,  is indeed much nicer, thank you very much for following up!
